using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Weaver.Permitting.DB
{
    public class _Seed
    {
        public _Seed() 
        { 
            using(var db = new PermittingDB())
            {
                if (db.MasterDocuments.Where(x => x.DocumentName == "City or County Utility Availability letter").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "City or County Utility Availability letter", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Civil Plans").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Civil Plans", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "City of Lake City Accessibility Letter").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "City of Lake City Accessibility Letter", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Town of Fort White Permit Approval Letter").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Town of Fort White Permit Approval Letter", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Zoning Application").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Zoning Application", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Boundary Sketch or Survey with bearings and dimensions").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Boundary Sketch or Survey with bearings and dimensions", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Aerial Photo").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Aerial Photo", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Concurrency Impact Analysis").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Concurrency Impact Analysis", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Construction Lien Law Form").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Construction Lien Law Form", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Comprehensive Plan Consistency Analysis").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Comprehensive Plan Consistency Analysis", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Legal Description with Tax Parcel Number").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Legal Description with Tax Parcel Number", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Proof of Ownership").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Proof of Ownership", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Agent Authorization Form").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Agent Authorization Form", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Proof of Payment of Taxes").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Proof of Payment of Taxes", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Proposed Text to the Comprehensive Plan").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Proposed Text to the Comprehensive Plan", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Survey prepared by a registered surveyor").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Survey prepared by a registered surveyor", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Fire Department Access and Water Supply Plan").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Fire Department Access and Water Supply Plan", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Other document as required").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Other document as required", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Proposed Text to the Land Development Regulations (“LDRs”) ").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Proposed Text to the Land Development Regulations (“LDRs”) ", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Contractor Letter of Authorization").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Contractor Letter of Authorization", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Vicinity Map ").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Vicinity Map ", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Site Plan").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Site Plan", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Storm Water Management Plan").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Storm Water Management Plan", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Analysis of the Requirements of Section 16.2 of the Land Development Regulations").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Analysis of the Requirements of Section 16.2 of the Land Development Regulations", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Analysis of Section 12.2.1.(3)(h) of the Land Development Regulations (“LDRs”)").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Analysis of Section 12.2.1.(3)(h) of the Land Development Regulations (“LDRs”)", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Proposed Lot Map").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Proposed Lot Map", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Personal Identification and Proof of Relationship").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Personal Identification and Proof of Relationship", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Family Relationship Residence Agreement Affidavit").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Family Relationship Residence Agreement Affidavit", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Legal Description of Parent Parcel with Acreage").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Legal Description of Parent Parcel with Acreage", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Legal Description of Property to be Deeded to Immediate Family Member with Acreage").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Legal Description of Property to be Deeded to Immediate Family Member with Acreage", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Corporate Articles listing the owner or POA form or Executor documents").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Corporate Articles listing the owner or POA form or Executor documents", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Legal Description of Parent Parcel with Immediate Family Member Lot Removed with Acreage").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Legal Description of Parent Parcel with Immediate Family Member Lot Removed with Acreage", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Preliminary Plat").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Preliminary Plat", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Construction Plans").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Construction Plans", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Final Plats").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Final Plats", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Analysis of Section 12.3.1.2 of the Land Development Regulations (“LDRs”)").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Analysis of Section 12.3.1.2 of the Land Development Regulations (“LDRs”)", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Application Packet").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Application Packet", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Pre-Slab Elevation Certification").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Pre-Slab Elevation Certification", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Cover Sheet Details").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Cover Sheet Details", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Design Professionals Letter").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Design Professionals Letter", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Electrical Plans").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Electrical Plans", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "911 Address form").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "911 Address form", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Elevation Certificate for Finished Construction").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Elevation Certificate for Finished Construction", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Emails").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Emails", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Energy Code Forms").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Energy Code Forms", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Engineers letter confirming their requirements").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Engineers letter confirming their requirements", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Fire Wall Layout").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Fire Wall Layout", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Floor Joist Engineering").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Floor Joist Engineering", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Addendums").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Addendums", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Floor Rise Certification").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Floor Rise Certification", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "General Notes_Job Information").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "General Notes_Job Information", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Land Owner Affidavit").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Land Owner Affidavit", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Leasee Authority to Sign Letter").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Leasee Authority to Sign Letter", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Life Safety Plans").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Life Safety Plans", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Manual J Forms").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Manual J Forms", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Mechanical Plans_Fire System_Alarm System").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Mechanical Plans_Fire System_Alarm System", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Metal Building Plans").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Metal Building Plans", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "MH Application Packet").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "MH Application Packet", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "AHRI Certificate or Accredited Laboratory or Manufacturers Letter or FL Engineers Letter").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "AHRI Certificate or Accredited Laboratory or Manufacturers Letter or FL Engineers Letter", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "MH Installers Authorization").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "MH Installers Authorization", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Mobile Home Permit Worksheets_Blocking Diagram").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Mobile Home Permit Worksheets_Blocking Diagram", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Solar Module Data and Components").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Solar Module Data and Components", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "New Well letter").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "New Well letter", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Notice to Owner Barrier Requirements").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Notice to Owner Barrier Requirements", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Other").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Other", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Out of County Mobile Home Inspection Report").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Out of County Mobile Home Inspection Report", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Owner and Contractor Signature Page").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Owner and Contractor Signature Page", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Owner Disclosure Statement").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Owner Disclosure Statement", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Application Information Page").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Application Information Page", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Plumbing Plans").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Plumbing Plans", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Product Approval Code Specifications Form").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Product Approval Code Specifications Form", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Property Appraiser Parcel Details Printed Page").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Property Appraiser Parcel Details Printed Page", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Recorded Deed").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Recorded Deed", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Recorded Notice of Commencement").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Recorded Notice of Commencement", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Residential or Commercial Checklist").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Residential or Commercial Checklist", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Architectural Plans").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Architectural Plans", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Roof Inspection Affidavit by contractor").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Roof Inspection Affidavit by contractor", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Roof Layout Plan").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Roof Layout Plan", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Roof Pictures").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Roof Pictures", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Scope of Work_Job Details list").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Scope of Work_Job Details list", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Sealed Foundation Plans").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Sealed Foundation Plans", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Sealed Modular Plans").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Sealed Modular Plans", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Sealed Pool Plans").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Sealed Pool Plans", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Septic Approval Paperwork").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Septic Approval Paperwork", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Backup material").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Backup material", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Sign Design and Description Details").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Sign Design and Description Details", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Site Plan").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Site Plan", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Site Survey").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Site Survey", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Special Temporary Use Affidavit").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Special Temporary Use Affidavit", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "State Road Driveway Permit").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "State Road Driveway Permit", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Structural Analysis Report").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Structural Analysis Report", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Structural Engineering and Wind Load Calculations").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Structural Engineering and Wind Load Calculations", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Blower Door Test Results").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Blower Door Test Results", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Subcontractor Form").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Subcontractor Form", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Subdivision Plat").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Subdivision Plat", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Surveyor letter giving the Finished Floor Elevation").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Surveyor letter giving the Finished Floor Elevation", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Suwannee River Water Management Permit").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Suwannee River Water Management Permit", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "System Design and Details").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "System Design and Details", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Termite Certificate_Final").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Termite Certificate_Final", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Termite Treatment_Initial").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Termite Treatment_Initial", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Truss Engineering").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Truss Engineering", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Used Mobile Home Inspection Report").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Used Mobile Home Inspection Report", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Zoning Approval Documents").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Zoning Approval Documents", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Documentation").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Documentation", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Certificate").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Certificate", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Letter").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Letter", DocumentNumber = 1, IsActive = true }); }
                if (db.MasterDocuments.Where(x => x.DocumentName == "Fire Department Letter").SingleOrDefault() == null) { db.MasterDocuments.Add(new MasterDocument() { DocumentName = "Fire Department Letter", DocumentNumber = 1, IsActive = true }); }

                if (db.ApplicationProjectTypes.Where(x => x.Name == "RESIDENTIAL").SingleOrDefault() == null) { db.ApplicationProjectTypes.Add(new ApplicationProjectType() { Name = "RESIDENTIAL" }); }
                if (db.ApplicationProjectTypes.Where(x => x.Name == "COMMERCIAL").SingleOrDefault() == null) { db.ApplicationProjectTypes.Add(new ApplicationProjectType() { Name = "COMMERCIAL" }); }

                if (db.FinanceAccountTypes.Where(x => x.AccountType == "C").SingleOrDefault() == null) { db.FinanceAccountTypes.Add(new FinanceAccountType() { AccountType = "C", Description = "CASH" }); }
                if (db.FinanceAccountTypes.Where(x => x.AccountType == "E").SingleOrDefault() == null) { db.FinanceAccountTypes.Add(new FinanceAccountType() { AccountType = "E", Description = "EXPENSE" }); }
                if (db.FinanceAccountTypes.Where(x => x.AccountType == "L").SingleOrDefault() == null) { db.FinanceAccountTypes.Add(new FinanceAccountType() { AccountType = "L", Description = "LIABILITY" }); }
                if (db.FinanceAccountTypes.Where(x => x.AccountType == "R").SingleOrDefault() == null) { db.FinanceAccountTypes.Add(new FinanceAccountType() { AccountType = "R", Description = "REVENUE" }); }


                //Departments
                if (db.Departments.Where(x => x.Name == "BUILDING DEPARTMENT").SingleOrDefault() == null) { db.Departments.Add(new Department() { Name = "BUILDING DEPARTMENT" }); };
                if (db.Departments.Where(x => x.Name == "ZONING DEPARTMENT").SingleOrDefault() == null) { db.Departments.Add(new Department() { Name = "ZONING DEPARTMENT" }); };
                if (db.Departments.Where(x => x.Name == "ADDRESSING").SingleOrDefault() == null) { db.Departments.Add(new Department() { Name = "ADDRESSING" }); };
                if (db.Departments.Where(x => x.Name == "PUBLIC WORKS").SingleOrDefault() == null) { db.Departments.Add(new Department() { Name = "PUBLIC WORKS" }); };

                //Payment Types
                if (db.PaymentTypes.Where(x => x.Name == "CASH").SingleOrDefault() == null) { db.PaymentTypes.Add(new PaymentType() { Name = "CASH" }); };
                if (db.PaymentTypes.Where(x => x.Name == "CHECK").SingleOrDefault() == null) { db.PaymentTypes.Add(new PaymentType() { Name = "CHECK" }); };
                if (db.PaymentTypes.Where(x => x.Name == "MONEY ORDER").SingleOrDefault() == null) { db.PaymentTypes.Add(new PaymentType() { Name = "MONEY ORDER" }); };
                if (db.PaymentTypes.Where(x => x.Name == "CREDIT CARD").SingleOrDefault() == null) { db.PaymentTypes.Add(new PaymentType() { Name = "CREDIT CARD" }); };
                if (db.PaymentTypes.Where(x => x.Name == "ACH").SingleOrDefault() == null) { db.PaymentTypes.Add(new PaymentType() { Name = "ACH" }); };

                //driveway types
                if (db.DrivewayAccessTypes.Where(x => x.Description == "New Driveway Permit").SingleOrDefault() == null) { db.DrivewayAccessTypes.Add(new DrivewayAccessType() { Description = "New Driveway Permit" }); };
                if (db.DrivewayAccessTypes.Where(x => x.Description == "Existing Drive").SingleOrDefault() == null) { db.DrivewayAccessTypes.Add(new DrivewayAccessType() { Description = "Existing Drive" }); };
                if (db.DrivewayAccessTypes.Where(x => x.Description == "Private Drive").SingleOrDefault() == null) { db.DrivewayAccessTypes.Add(new DrivewayAccessType() { Description = "Private Drive" }); };
                if (db.DrivewayAccessTypes.Where(x => x.Description == "D.O.T. Permit").SingleOrDefault() == null) { db.DrivewayAccessTypes.Add(new DrivewayAccessType() { Description = "D.O.T. Permit" }); };


                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "102-0000-342.50-00" && x.FeeName == "Application Fee" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "Application Fee", DepartmentId = 1, Description = "Application Fee - $15.00", CalculationString = "15.00", IsBuildingPermitFee = false, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "102-0000-329.10-00" && x.FeeName == "Development Permit" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "Development Permit", DepartmentId = 1, Description = "Flat Fee $50.00", CalculationString = "50.00", IsBuildingPermitFee = false, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "102-0000-322.10-00" && x.FeeName == "Revisions After Permitted" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "Revisions After Permitted", DepartmentId = 1, Description = "Flat Fee $30.00", CalculationString = "30.00", IsBuildingPermitFee = false, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "102-0000-322.10-00" && x.FeeName == "Culvert" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "Culvert", DepartmentId = 1, Description = "Flat Fee $25.00", CalculationString = "25.00", IsBuildingPermitFee = false, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "101-0000-344.90-00" && x.FeeName == "Culvert Waiver" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "Culvert Waiver", DepartmentId = 1, Description = "Flat Fee $50.00", CalculationString = "50.00", IsBuildingPermitFee = false, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "102-0000-208.10-01" && x.FeeName == "Certificate Fee" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "Certificate Fee", DepartmentId = 1, Description = "{BuildingPermitFee} * .01m (minimum $2.00 fee)", CalculationString = "if({BuildingPermitFee} * .01 < 2.00, 2.00, {BuildingPermitFee} * .01)", IsBuildingPermitFee = false, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "102-0000-208.10-01" && x.FeeName == "DBPR - Surcharge / Radon" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "DBPR - Surcharge / Radon", DepartmentId = 1, Description = "Building Permit Fee * .015 (minimum $2.00 fee)", CalculationString = "if({BuildingPermitFee} * .015 < 2.00, 2.00, {BuildingPermitFee} * .015)", IsBuildingPermitFee = false, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "102-0000-325.22-22" && x.FeeName == "Fire Assessment Residential" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "Fire Assessment Residential", DepartmentId = 1, Description = "A stepped fee calculated on acres.", CalculationString = "((269.98 / 12.0) * {CurrentFiscalMonth}) + if({ParcelAcres} > 6, ((3.01 / 12.0) * {CurrentFiscalMonth}), 0) + if( {ParcelAcres} > 160, .0306 * ({ParcelAcres} - 160), 0)", IsBuildingPermitFee = false, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "102-0000-325.22-22" && x.FeeName == "Fire Assessment Commercial" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "Fire Assessment Commercial", DepartmentId = 1, Description = "Total Area: ((TotalSqft * .0787)/12) * Fiscal Month", CalculationString = "(({TotalSquareFootage} * .0787)/12) * {CurrentFiscalMonth}", IsBuildingPermitFee = false, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "102-0000-325.22-22" && x.FeeName == "Fire Assessment Industrial Warehouse" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "Fire Assessment Industrial Warehouse", DepartmentId = 1, Description = "Total Area: ((TotalSqft * .0672)/12) * FiscalMonth", CalculationString = "(({TotalSquareFootage} * .0672)/12) * {CurrentFiscalMonth}", IsBuildingPermitFee = false, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "102-0000-325.22-22" && x.FeeName == "Fire Assessment Institutional" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "Fire Assessment Institutional", DepartmentId = 1, Description = "Total Area: ((TotalSqFT * .13)/12) * FiscalMonth", CalculationString = "(({TotalSquareFootage} * .13)/12) * {CurrentFiscalMonth}", IsBuildingPermitFee = false, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "102-0000-322.10-00" && x.FeeName == "Mobile Home - Single Wide" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "Mobile Home - Single Wide", DepartmentId = 1, Description = "Flat Fee $250.00", CalculationString = "250.00", IsBuildingPermitFee = false, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "102-0000-325.20-22" && x.FeeName == "Solid Waste Assessment" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "Solid Waste Assessment", DepartmentId = 1, Description = "((198.06 / 12.00) * FiscalMonth", CalculationString = "((198.06 / 12.00) * {CurrentFiscalMonth}", IsBuildingPermitFee = false, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "102-0000-342.50-01" && x.FeeName == "Re-Inspections" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "Re-Inspections", DepartmentId = 1, Description = "Flat Fee $50.00", CalculationString = "50.00", IsBuildingPermitFee = false, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "102-0000-342.50-02" && x.FeeName == "Electrical Service Change" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "Electrical Service Change", DepartmentId = 1, Description = "Flat Fee $50.00", CalculationString = "50.00", IsBuildingPermitFee = false, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "102-0000-342.50-03" && x.FeeName == "Pre-Inspections" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "Pre-Inspections", DepartmentId = 1, Description = "Flat Fee $50.00", CalculationString = "50.00", IsBuildingPermitFee = false, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "102-0000-322.10-00" && x.FeeName == "Building Permit Fee Based on Total Area (Sqft)" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "Building Permit Fee Based on Total Area (Sqft)", DepartmentId = 1, Description = "((TotalSqft * 60.00)/1000) * 8.00)", CalculationString = "(({TotalSquareFootage} * 60.00)/1000) * 8.00", IsBuildingPermitFee = true, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "102-0000-322.10-00" && x.FeeName == "Building Permit Fee Based on Construction Cost" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "Building Permit Fee Based on Construction Cost", DepartmentId = 1, Description = "Minimum Flat Fee of 100.00 or (Project Cost/1000) * 8.00", CalculationString = "if((({TotalConstructionCost}/1000) * 8.00) < 100, 100.00, ({TotalConstructionCost}/1000) * 8.00)", IsBuildingPermitFee = true, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "102-0000-349.10-01" && x.FeeName == "Plan Review" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "Plan Review", DepartmentId = 1, Description = "Minimum Flat Fee of 75 or (Building Permit Fee * .25)", CalculationString = "ifs(({BuildingPermitFee} * .25) < 75.00, 75.00, ({BuildingPermitFee} * .25))", IsBuildingPermitFee = false, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "102-0000-329.10-00" && x.FeeName == "Zoning Certification Fee" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "Zoning Certification Fee", DepartmentId = 1, Description = "Flat Fee $50.00", CalculationString = "50.00", IsBuildingPermitFee = false, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "102-0000-329.10-00" && x.FeeName == "Flood Zone Certification Fee" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "Flood Zone Certification Fee", DepartmentId = 1, Description = "Flat Fee $25.00", CalculationString = "25.00", IsBuildingPermitFee = false, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "102-0000-325.22-22" && x.FeeName == "Fire Assessment - 6 months" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "Fire Assessment - 6 months", DepartmentId = 1, Description = "((219.98 / 12.0) * 6", CalculationString = "((219.98 / 12.0) * 6", IsBuildingPermitFee = false, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "102-0000-322.10-00" && x.FeeName == "Mobile Home - Double Wide" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "Mobile Home - Double Wide", DepartmentId = 1, Description = "Flat Fee $300.00", CalculationString = "300.00", IsBuildingPermitFee = false, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "102-0000-325.20-22" && x.FeeName == "Solid Waste Assessment - 6 months" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "Solid Waste Assessment - 6 months", DepartmentId = 1, Description = "((198.06 / 12.00) * 6)", CalculationString = "((198.06 / 12.00) * 6)", IsBuildingPermitFee = false, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "102-0000-322.10-00" && x.FeeName == "Culvert in Ft. White" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "Culvert in Ft. White", DepartmentId = 1, Description = "Flat Fee $50.00", CalculationString = "50.00", IsBuildingPermitFee = false, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "101-0000-344.90-00" && x.FeeName == "Culvert Waiver in Ft. White" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "Culvert Waiver in Ft. White", DepartmentId = 1, Description = "Flat Fee $25.00", CalculationString = "25.00", IsBuildingPermitFee = false, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "102-0000-342.50-00" && x.FeeName == "Lake City Technology Fee" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "Lake City Technology Fee", DepartmentId = 1, Description = "Lake City Technology Fee", CalculationString = "0.00", IsBuildingPermitFee = false, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "102-0000-322.20-00" && x.FeeName == "Lake City New Electrical Permit Fee (Commerical & Residential)" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "Lake City New Electrical Permit Fee (Commerical & Residential)", DepartmentId = 1, Description = "Lake City New Electrical Permit Fee  (Commerical & Residential)", CalculationString = "0.00", IsBuildingPermitFee = false, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "102-0000-322.20-00" && x.FeeName == "Lake City Existing Electrical Permit Fee" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "Lake City Existing Electrical Permit Fee", DepartmentId = 1, Description = "Lake City Existing Electrical Permit Fee", CalculationString = "0.00", IsBuildingPermitFee = false, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "102-0000-322.30-00" && x.FeeName == "Lake City Gas Permit Fee" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "Lake City Gas Permit Fee", DepartmentId = 1, Description = "Lake City Gas Permit Fee", CalculationString = "0.00", IsBuildingPermitFee = false, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "102-0000-322.30-00" && x.FeeName == "Lake City Plumbing Permit Fee" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "Lake City Plumbing Permit Fee", DepartmentId = 1, Description = "Lake City Plumbing Permit Fee", CalculationString = "0.00", IsBuildingPermitFee = false, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "102-0000-322.31-00" && x.FeeName == "Lake City Mechanical Permit Fee" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "Lake City Mechanical Permit Fee", DepartmentId = 1, Description = "Lake City Mechanical Permit Fee", CalculationString = "0.00", IsBuildingPermitFee = false, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "102-0000-322.10-00" && x.FeeName == "Mobile Home - Triple Wide" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "Mobile Home - Triple Wide", DepartmentId = 1, Description = "Flat Fee $350.00", CalculationString = "350.00", IsBuildingPermitFee = false, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "102-0000-322.10-00" && x.FeeName == "Right-of-Way Access/Driveway" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "Right-of-Way Access/Driveway", DepartmentId = 1, Description = "Flat Fee $150.00", CalculationString = "150.00", IsBuildingPermitFee = false, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "102-0000-322.10-00" && x.FeeName == "Modular Home" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "Modular Home", DepartmentId = 1, Description = "Flat Fee $350.00", CalculationString = "350.00", IsBuildingPermitFee = false, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "102-0000-329.10-00" && x.FeeName == "RV - Special Temporary Use Permit" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "RV - Special Temporary Use Permit", DepartmentId = 1, Description = "Flat Fee $50.00", CalculationString = "50.00", IsBuildingPermitFee = false, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "102-0000-322.10-00" && x.FeeName == "Relocation" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "Relocation", DepartmentId = 1, Description = "Flat Fee $175.00", CalculationString = "175.00", IsBuildingPermitFee = false, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "102-0000-322.10-00" && x.FeeName == "Reconnection/Safety Insp." && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "Reconnection/Safety Insp.", DepartmentId = 1, Description = "Flat Fee $75.00", CalculationString = "75.00", IsBuildingPermitFee = false, IsContractorFee = false }); }
                if (db.Fees.Where(x => x.RevenueAccountAccountNumber == "102-0000-322.10-00" && x.FeeName == "Utility/Pump Pole or Mobile Home Pole" && x.DepartmentId == 1).SingleOrDefault() == null) { db.Fees.Add(new Fee() { FeeName = "Utility/Pump Pole or Mobile Home Pole", DepartmentId = 1, Description = "Flat Fee $50.00", CalculationString = "50.00", IsBuildingPermitFee = false, IsContractorFee = false }); }

                if (db.ApplicationTypes.Where(x => x.Name == "Variances").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 2, Name = "Variances", IsPublic = true, MigrationID = 1 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "Special Exceptions").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 2, Name = "Special Exceptions", IsPublic = true, MigrationID = 2 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "Site Development Plan").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 2, Name = "Site Development Plan", IsPublic = true, MigrationID = 3 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "Comprehensive Plan Text Amendment").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 2, Name = "Comprehensive Plan Text Amendment", IsPublic = true, MigrationID = 4 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "Site Specific Amendment to the Official Zoning Atlas (Rezoning)").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 2, Name = "Site Specific Amendment to the Official Zoning Atlas (Rezoning)", IsPublic = true, MigrationID = 5 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "Comprehensive Plan Amendment").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 2, Name = "Comprehensive Plan Amendment", IsPublic = true, MigrationID = 6 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "LDR Text Amendment").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 2, Name = "LDR Text Amendment", IsPublic = true, MigrationID = 7 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "Minor Subdivision").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 2, Name = "Minor Subdivision", IsPublic = true, MigrationID = 8 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "Subdivision").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 2, Name = "Subdivision", IsPublic = true, MigrationID = 9 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "Special Family Lot Permit").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 2, Name = "Special Family Lot Permit", IsPublic = true, MigrationID = 10 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "Special Temporary Use").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 2, Name = "Special Temporary Use", IsPublic = true, MigrationID = 11 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "Special Permit").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 2, Name = "Special Permit", IsPublic = true, MigrationID = 12 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "Division of Land").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 2, Name = "Division of Land", IsPublic = true, MigrationID = 13 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "Swimming Pool and Spa").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 1, Name = "Swimming Pool and Spa", IsPublic = true, MigrationID = 14 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "Roof Replacement or Repair").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 1, Name = "Roof Replacement or Repair", IsPublic = true, MigrationID = 15 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "Air Conditioner Replacement or Repair").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 1, Name = "Air Conditioner Replacement or Repair", IsPublic = true, MigrationID = 16 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "Mobile Home").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 1, Name = "Mobile Home", IsPublic = true, MigrationID = 17 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "New Residential Construction").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 1, Name = "New Residential Construction", IsPublic = true, MigrationID = 18 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "911 Address Application").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 1, Name = "911 Address Application", IsPublic = true, MigrationID = 19 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "Subdivision Variance").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 2, Name = "Subdivision Variance", IsPublic = true, MigrationID = 20 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "Signs - New or Existing").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 1, Name = "Signs - New or Existing", IsPublic = true, MigrationID = 21 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "Electrical Service Upgrade or Change").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 1, Name = "Electrical Service Upgrade or Change", IsPublic = true, MigrationID = 22 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "Electrical Service").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 1, Name = "Electrical Service", IsPublic = true, MigrationID = 23 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "Remodel").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 1, Name = "Remodel", IsPublic = true, MigrationID = 24 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "New Commercial Construction").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 1, Name = "New Commercial Construction", IsPublic = true, MigrationID = 25 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "Culvert").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 1, Name = "Culvert", IsPublic = true, MigrationID = 26 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "Culvert Waiver").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 1, Name = "Culvert Waiver", IsPublic = true, MigrationID = 28 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "Demolition").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 1, Name = "Demolition", IsPublic = true, MigrationID = 29 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "Solar Power System").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 1, Name = "Solar Power System", IsPublic = true, MigrationID = 30 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "Storage Building").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 1, Name = "Storage Building", IsPublic = true, MigrationID = 31 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "RV - Recreational Vehicle").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 1, Name = "RV - Recreational Vehicle", IsPublic = true, MigrationID = 32 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "Screen Enclosure").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 1, Name = "Screen Enclosure", IsPublic = true, MigrationID = 33 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "Communications Tower").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 1, Name = "Communications Tower", IsPublic = true, MigrationID = 34 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "Modular Building - Residential or Commercial").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 1, Name = "Modular Building - Residential or Commercial", IsPublic = true, MigrationID = 35 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "Additions").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 1, Name = "Additions", IsPublic = true, MigrationID = 36 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "Alcohol License").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 2, Name = "Alcohol License", IsPublic = true, MigrationID = 37 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "Statement of Land Use and Zoning").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 2, Name = "Statement of Land Use and Zoning", IsPublic = true, MigrationID = 38 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "Flood Determination Letter").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 2, Name = "Flood Determination Letter", IsPublic = true, MigrationID = 39 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "Miscelleneous Zoning Application").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 2, Name = "Miscelleneous Zoning Application", IsPublic = true, MigrationID = 40 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "Right-of-Way Access/Driveway").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 1, Name = "Right-of-Way Access/Driveway", IsPublic = true, MigrationID = 46 }); }
                if (db.ApplicationTypes.Where(x => x.Name == "Generator").SingleOrDefault() == null) { db.ApplicationTypes.Add(new ApplicationType() { DepartmentId = 1, Name = "Generator", IsPublic = true, MigrationID = 47 }); }

                if (db.BuildingCodeConstructionTypes.Where(x => x.ConstructionType == "I").SingleOrDefault() == null) { db.BuildingCodeConstructionTypes.Add(new BuildingCodeConstructionType() { ConstructionType = "I" }); }
                if (db.BuildingCodeConstructionTypes.Where(x => x.ConstructionType == "II").SingleOrDefault() == null) { db.BuildingCodeConstructionTypes.Add(new BuildingCodeConstructionType() { ConstructionType = "II" }); }
                if (db.BuildingCodeConstructionTypes.Where(x => x.ConstructionType == "III").SingleOrDefault() == null) { db.BuildingCodeConstructionTypes.Add(new BuildingCodeConstructionType() { ConstructionType = "III" }); }
                if (db.BuildingCodeConstructionTypes.Where(x => x.ConstructionType == "IV").SingleOrDefault() == null) { db.BuildingCodeConstructionTypes.Add(new BuildingCodeConstructionType() { ConstructionType = "IV" }); }
                if (db.BuildingCodeConstructionTypes.Where(x => x.ConstructionType == "V").SingleOrDefault() == null) { db.BuildingCodeConstructionTypes.Add(new BuildingCodeConstructionType() { ConstructionType = "V" }); }

                if (db.BuildingCodeOccupancyTypes.Where(x => x.OccupancyType == "Residential").SingleOrDefault() == null) { db.BuildingCodeOccupancyTypes.Add(new BuildingCodeOccupancyType() { OccupancyType = "Residential" }); }
                if (db.BuildingCodeOccupancyTypes.Where(x => x.OccupancyType == "Mercantile").SingleOrDefault() == null) { db.BuildingCodeOccupancyTypes.Add(new BuildingCodeOccupancyType() { OccupancyType = "Mercantile" }); }
                if (db.BuildingCodeOccupancyTypes.Where(x => x.OccupancyType == "Storage").SingleOrDefault() == null) { db.BuildingCodeOccupancyTypes.Add(new BuildingCodeOccupancyType() { OccupancyType = "Storage" }); }
                if (db.BuildingCodeOccupancyTypes.Where(x => x.OccupancyType == "Utility & Misc").SingleOrDefault() == null) { db.BuildingCodeOccupancyTypes.Add(new BuildingCodeOccupancyType() { OccupancyType = "Utility & Misc" }); }
                if (db.BuildingCodeOccupancyTypes.Where(x => x.OccupancyType == "Daycare Occupancy").SingleOrDefault() == null) { db.BuildingCodeOccupancyTypes.Add(new BuildingCodeOccupancyType() { OccupancyType = "Daycare Occupancy" }); }
                if (db.BuildingCodeOccupancyTypes.Where(x => x.OccupancyType == "Business").SingleOrDefault() == null) { db.BuildingCodeOccupancyTypes.Add(new BuildingCodeOccupancyType() { OccupancyType = "Business" }); }
                if (db.BuildingCodeOccupancyTypes.Where(x => x.OccupancyType == "Education").SingleOrDefault() == null) { db.BuildingCodeOccupancyTypes.Add(new BuildingCodeOccupancyType() { OccupancyType = "Education" }); }
                if (db.BuildingCodeOccupancyTypes.Where(x => x.OccupancyType == "Factory").SingleOrDefault() == null) { db.BuildingCodeOccupancyTypes.Add(new BuildingCodeOccupancyType() { OccupancyType = "Factory" }); }
                if (db.BuildingCodeOccupancyTypes.Where(x => x.OccupancyType == "High Hazard").SingleOrDefault() == null) { db.BuildingCodeOccupancyTypes.Add(new BuildingCodeOccupancyType() { OccupancyType = "High Hazard" }); }
                if (db.BuildingCodeOccupancyTypes.Where(x => x.OccupancyType == "Institutional").SingleOrDefault() == null) { db.BuildingCodeOccupancyTypes.Add(new BuildingCodeOccupancyType() { OccupancyType = "Institutional" }); }

                if (db.BuildingCodeElements.Where(x => x.Element == "A").SingleOrDefault() == null) { db.BuildingCodeElements.Add(new BuildingCodeElement() { Element = "A" }); }
                if (db.BuildingCodeElements.Where(x => x.Element == "B").SingleOrDefault() == null) { db.BuildingCodeElements.Add(new BuildingCodeElement() { Element = "B" }); }
                if (db.BuildingCodeElements.Where(x => x.Element == "A&B").SingleOrDefault() == null) { db.BuildingCodeElements.Add(new BuildingCodeElement() { Element = "A&B" }); }
                if (db.BuildingCodeElements.Where(x => x.Element == "HT").SingleOrDefault() == null) { db.BuildingCodeElements.Add(new BuildingCodeElement() { Element = "HT" }); }
                if (db.BuildingCodeElements.Where(x => x.Element == "A&HT").SingleOrDefault() == null) { db.BuildingCodeElements.Add(new BuildingCodeElement() { Element = "A&HT" }); }
                if (db.BuildingCodeElements.Where(x => x.Element == "B&HT").SingleOrDefault() == null) { db.BuildingCodeElements.Add(new BuildingCodeElement() { Element = "B&HT" }); }
                if (db.BuildingCodeElements.Where(x => x.Element == "A&B&HT").SingleOrDefault() == null) { db.BuildingCodeElements.Add(new BuildingCodeElement() { Element = "A&B&HT" }); }
            }
        }
    }
}
